// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://suyesccpwxrmbdetqoir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1eWVzY2Nwd3hybWJkZXRxb2lyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NDUzNjAsImV4cCI6MjA3NDIyMTM2MH0.PtA_IfSraAUNZMliDakAt1CyhQM5hVRLBYsh22f5NGQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});